
# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
#version: 2.1
#
#job:
#  build: # The job name
#    machine: true # executor
#    steps:
#      run:
#        make
#workflow:
#  version: 2.1
#  workflow_test: # workflow name
#    jobs:
#      build

version: 2.1
jobs:
  build:
    machine: true
    steps: 
      - checkout
      - run: git clone https://github.com/devinjh/project_3_elements.git
      - run: make
  #make:
  #  machine: true
  #  steps:
  #    - run: make

workflows:
  workflow:
    jobs:
      - build
      #- make