
# Using the latest version of CircleCI as of today (5/9/2019)
version: 2.1

# Listing out the jobs
jobs:
  # The build job
  build:
    # It's using bash commands, so it should be run on the mahine
    machine: true
    steps:
      - checkout # Setting up an image to work in
      - run: git clone https://github.com/devinjh/project_3_elements.git # Downloading all the code from project repo
      - run: make # Running make to build the code
  #make:
  #  machine: true
  #  steps:
  #    - run: make
# Workflows
workflows:
  # The workflow
  workflow:
    # All the jobs that must be performed
    jobs:
      - build # Running the build job
      #- make