
# Using the latest version of CircleCI as of today (5/9/2019)
version: 2.1

# Listing out the jobs
jobs:
  # The job that builds the project
  build:
    # It's using bash commands, so it should be run on the mahine
    machine: true
    steps:
      - checkout # Setting up an image to work in
      - run: git clone https://github.com/devinjh/project_3_elements.git # Downloading all the code from project repo
      - run: make # Makes the argon2 executable
      - run: make bench # Makes the bench exectuable
      - run: make test # Makes the test exectuable, this verifies the installations
      - run: echo "The test will now begin" # Showing that the tests will begin
      - run: echo -n "password" | ./argon2 somesalt -i -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
      - run: echo -n "password" | ./argon2 somesalt -d -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
      - run: echo -n "password" | ./argon2 somesalt -id -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
      - run: echo -n "password" | ./argon2 abcdefghijk -i -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
      - run: echo -n "password" | ./argon2 abcdefghijk -d -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
      - run: echo -n "password" | ./argon2 abcdefghijk -id -t 2 -m 16 -p 4 -l 24 # This is a test to see if the program runs correctly
# Workflows
workflows:
  # The workflow
  workflow:
    # All the jobs that must be performed
    jobs:
      - build # Running the build job